FROM ruby:2.3.1

RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list

RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y vim
RUN apt-get install -y mysql-client
RUN apt-get install -y cron
RUN apt-get install -y rsyslog
